### ISSUE TITLE
Options request

### ISSUE THREAD

**Issue by juanpablob** [sindresorhus/strip-debug#17] opened 2018-01-23 17:20 UTC
Hi there!
Would be great to pass some options, like
`{
logging: true, // remove console.log
alerts: false // don't remove console.log
}
`

in order to avoid removing alerts, since some apps are still using alerts as legit dialogs for their users :)

Thanks!

**Comment by sindresorhus** [comment] 2018-01-23 18:03
Duplicate of #10

**Closed by sindresorhus** 2018-01-23 18:03 UTC
