### ISSUE TITLE
Is there a way to preserve alerts?

### ISSUE THREAD

**Issue by wzup** [sindresorhus/strip-debug#12] opened 2015-12-10 03:24 UTC
I have a React component that calls `alert("Some info message")` inside a function. The function is called as a `onClick` event handler. Because there is no way to set an inline attribute `onclick="alert('Some info message')"` in React, I have to do it this way:
```
var FooComponent= React.createClass({
    onOptionSelect: function(e) {
        e.preventDefault();
        alert('Some info message.');
        return;
    },
```
So I want to preserve `alert()`s. How to achieve it?

**Comment by wzup** [comment] 2015-12-10 05:38
```
var arlt = window.alert;
arlt('Some alert message.');
```

**Comment by SamVerschueren** [comment] 2015-12-10 07:22
Usually it's not a good idea to use `alert`. Those boxes are very ugly and not user friendly. Implement your own notification box or use one of the many open source alert boxes.

**Comment by sindresorhus** [comment] 2015-12-10 09:35
Duplicate of https://github.com/sindresorhus/strip-debug/issues/10.

You really shouldn't use `alert()` as it blocks the whole page.

**Comment by sindresorhus** [comment] 2015-12-10 09:36
https://github.com/jaredreich/notie.js is pretty good.

**Closed by sindresorhus** 2015-12-10 09:35 UTC

**Comment by ncla** [comment] 2016-07-16 13:24
It shouldn't be up to you to decide what the developer wants to do alerts, but rather the developer himself by providing options for it.

**Comment by sindresorhus** [comment] 2016-07-16 13:59
@ncla It's not up to me to decide what developers do, however, it's totally up to me how to make my modules. [`alert()` is really bad](http://stackoverflow.com/questions/8825384/alert-is-bad-really) and I don't want developers falling into the trap of using it.

**Comment by ncla** [comment] 2016-07-16 14:09
I am well aware of it's issues. 

In my and wzup's case however, we ended up using that work-around, where I would have preferred to set an option for this module, rather than modifying the project code.

If you are fine with the fact that people use that workaround as a solution, then I guess there's not much point discussing this any further.

**Comment by fabiocaccamo** [comment] 2021-08-24 18:04
@ncla thank you. 
It is really annoying have not the possibility to exclude `alert` calls from being stripped.
